### ISSUE TITLE
Cannot install app

### ISSUE THREAD

**Issue by neobenedict** [MathewSachin/Fate-Grand-Automata#126]
On Nox 6.3.0.8 / android 5

```W/PackageManager( 1792): Failed collect during installPackageLI
W/PackageManager( 1792): android.content.pm.PackageParser$PackageParserException: Package /data/app/vmdl112499614.tmp/base.apk has no certificates at entry AndroidManifest.xml
W/PackageManager( 1792):        at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1099)
W/PackageManager( 1792):        at android.content.pm.PackageParser.collectCertificates(PackageParser.java:1049)
W/PackageManager( 1792):        at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:10804)
W/PackageManager( 1792):        at com.android.server.pm.PackageManagerService.access$2300(PackageManagerService.java:236)
W/PackageManager( 1792):        at com.android.server.pm.PackageManagerService$6.run(PackageManagerService.java:8858)
W/PackageManager( 1792):        at android.os.Handler.handleCallback(Handler.java:739)
W/PackageManager( 1792):        at android.os.Handler.dispatchMessage(Handler.java:95)
W/PackageManager( 1792):        at android.os.Looper.loop(Looper.java:135)
W/PackageManager( 1792):        at android.os.HandlerThread.run(HandlerThread.java:61)
W/PackageManager( 1792):        at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

You seem to have not signed your app.

**Comment by neobenedict** [comment]
Never mind, I see the minimum android version.
