### ISSUE TITLE
Error. Using AutoSkill Skill Levels

### ISSUE THREAD

**Issue by NotAMemeber** [MathewSachin/Fate-Grand-Automata#235]
Jp/skill_ten.png

java.io.FileNotFoundException: Jp/skill_ten.png
	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:845)
	at android.content.res.AssetManager.open(AssetManager.java:822)
	at b.a.a.j.h.b(ImageLoader.kt:8)
	at b.a.a.b.b.n.v(Support.kt:17)
	at b.a.a.b.b.o.f(Support.kt:28)
	at p.m.j.a.a.h(ContinuationImpl.kt:2)
	at p.t.f.hasNext(SequenceBuilder.kt:10)
	at k.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:22)
	at b.a.a.b.b.p.invoke(Support.kt:7)
	at b.a.b.o.c(ScreenshotManager.kt:3)
	at b.a.a.b.b.n.z(Support.kt:1)
	at b.a.a.b.b.n.A(Support.kt:13)
	at b.a.a.b.a.a$b.invoke(com.android.tools.r8.jetbrains.kotlin-style lambda group:192)
	at b.a.a.b.a.a.u(AutoBattle.kt:86)
	at b.a.b.b.invoke(EntryPoint.kt:2)
	at p.l.a.run(Thread.kt:1)

Works fine without setting Skill Levels at 10/10/10

**Comment by MathewSachin** [comment]
JP?

**Comment by NotAMemeber** [comment]
Thanks!

**Comment by MathewSachin** [comment]
I did a new release just now (v0.18.0): https://github.com/MathewSachin/Fate-Grand-Automata/releases/tag/v0.18.0
Can you try if this works?

**Comment by NotAMemeber** [comment]
It works now!
