### ISSUE TITLE
Korean app issue

### ISSUE THREAD

**Issue by Lemonlimespicyashell** [MathewSachin/Fate-Grand-Automata#385]
> MAKE SURE YOU TESTED THE LATEST RELEASE.

> Did you look at other issues and the [Troubleshooting Guide](https://github.com/MathewSachin/Fate-Grand-Automata/wiki/Troubleshooting)?
Yes

**Describe the bug**
Script just stops. I think it has something to do with the Korean translation.

**Screenshots**
I don't have screenshots but I have a txt.file which shows what was the error.

I made the translation in English inside the bracket.

예상 밖의 오류: Conversion = '초'            (Unexpected error : conversion = 'second')

3번 중 1번 반복함                                       ( Repeated 1 in 3 times)
시간: 03:24                                              (Time: 03:24)
턴: 3                                                         (Turn: 3)

java.lang.Exception: 예상 밖의 오류: Conversion = '초'  (java.lang.Exception: Unexpected error : conversion = 'second')

3번 중 1번 반복함   ( Repeated 1 in 3 times)
시간: 03:24           (Time: 03:24)
턴: 3                        (Turn: 3)
	at b.a.a.c.a.a.w(AutoBattle.kt:35)
	at b.a.b.b.c(EntryPoint.kt:2)
	at k.n.a.run(Thread.kt:1)
Caused by: java.util.UnknownFormatConversionException: Conversion = '초'
	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2730)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2759)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2591)
	at java.util.Formatter.parse(Formatter.java:2524)
	at java.util.Formatter.format(Formatter.java:2472)
	at java.util.Formatter.format(Formatter.java:2426)
	at java.lang.String.format(String.java:2670)
	at android.content.res.Resources.getString(Resources.java:406)
	at android.content.Context.getString(Context.java:492)
	at b.a.a.m.b0.p(ScriptMessages.kt:1)
	at b.a.a.c.b.f.c(Card.kt:46)
	at b.a.b.t.c(ScreenshotManager.kt:3)
	at b.a.a.c.b.d.w(Battle.kt:25)
	at b.a.a.c.a.a$a.c(com.android.tools.r8.jetbrains.kotlin-style lambda group:59)
	at b.a.a.c.a.a.y(AutoBattle.kt:34)
	at b.a.a.c.a.a.w(AutoBattle.kt:34)
	... 2 more

**Video**
If relevant, include a video of the script running on your device with `Debug mode` ON
Recording functionality is available within the app in `More options`.

**Device Info (please fill atleast 'Device model'):**
Tested in multiple devices. Only happened when using Korean version.

**Comment by MathewSachin** [comment]
Yeah, I noticed it a few minutes before. Have done the fix. But, this error will only happen when the script can't detect face-cards, so shouldn't happen much often. I'll include the fix in the next release. Few more minor things to take care of right now.
Thanks for the heads up 👍
